### ISSUE TITLE
How is the Portugal dev scene

### ISSUE THREAD

**Issue by anthony2025** [SaraVieira/AMA#1]
Hi there :) I wonder how has been your experience working in tech in Portugal.
I would love to move around the world and experience living in other countries, but don't know much about Portugal, and am wondering if I should add it to my list.

Ps: I loved the postcss-caralho plugin 😂

**Comment by SaraVieira** [comment]
Hi man !

My experience has been pretty great, the great thing about portugal is that since there are not a lot of us (we are 10M) there are few programmers and even less female programmers so I never felt discrimination much quite the opposite.

You should totally visit portugal , the dev scene basically only exists in Lisbon and Porto, the two main towns so anyone who lives in other has to move but if you move to one of two yu will have meetups to go :)

Portugal is a great place to live if you have money because the people are really nice and stuff is super cheap so if you coming from another country you should totally stop by :)

Thanks 🎉
