### ISSUE TITLE
What brought you to programming?

### ISSUE THREAD

**Issue by siddharthkp** [SaraVieira/AMA#2]
How did you get started

**Comment by SaraVieira** [comment]
That's actually a funy story I already shared on twitter: https://twitter.com/NikkitaFTW/status/887399678396039169

This is 100% true 😝

After this whole thing I wanted to learn programming but unfortunately I did not have enough money to go to university so I had to go the 1yr course on Multimedia near my house because they gave us an internship, so I was an intern for 4 months ( only half way through did I figure out I wasn't getting paid ). I ended up learning everything on free stuff on the internet and just breaking stuff.

After the internship, I started writing articles to learn stuff and help others but then my car broke down and I had to buy one so I started working full time at the company I had interned in ( getting paid this time ) and from there I was at two more companies :)

**Comment by siddharthkp** [comment]
Sara, you're super cool. I hope you know that!

Also, I have to agree with @developit here, epic reverse psychology on your dad's part!

**Comment by SaraVieira** [comment]
@siddharthkp Thanks man ! You are not too shabby yourself :p 

I know , he won 😞
