### ISSUE TITLE
How is your daily routine ?

### ISSUE THREAD

**Issue by RahulReddy75** [SaraVieira/AMA#4]
Hi,
the question was basically ,with regards to how you organise the work for your company, open source contributions, constant learning and tech talks?
Sometimes i find it hard to get the balance.
May be some tips.

Cheers.!

**Comment by SaraVieira** [comment]
I am not a role model here in any way

First of all, I don't have an alarm, I wake up with the sun in my room ( I know! Living the life 😝 ).
I usually wake up around 9:30, get up and have coffee and right away start working from home, seeing what I have to do in that day and what I can start that may be faster.

After like 30m of this I get out of the house and go to work on my motorcycle so I am usually there at 10:30.

When I get there we have a stand-up and then start cracking, I try to divide the tasks so that none of them last more than a day and I can leave work feeling like I did all I should in that day and can go home rested :)

I usually get home at about 7:30PM so it's dinner time, make my dinner and after that, since I don't have a GF or anything I usually start working on Open Source projects because I honestly like it. There was a time that I actually forced myself to not work in Open Source because well I'm 25 I should want to get out of the house and do stuff but that's how I enjoy spending my time.

About the tech talks, It usually takes me about a day to write a decent talk then I practice for like an hour a day to make sure I memorized it all.

The learning mostly comes from twitter and following awesome people.

Hope this answers your question 🎉
